version: "3"
services:
  nginx:
    #容器镜像
    image: "nginx"
    #容器的名字 
    container_name: "nginx"
   #开放端口 
    ports:
      - "80:80"
      - "8080:8080"
    #绑定的主机目录  
    volumes:
      #nginx 额外的主机配置文件目录
      - "/data/web/config/nginx/conf.d:/etc/nginx/conf.d"
      #nginx 配置文件
      #- "/data/web/config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      #nginx数据文件目录
      - "/data/web/html:/web/html"
     #绑定的网络 
    networks:
     - "cmcc"
  
  
  php:
  #容器镜像
    image: "980198595/php-fpm:latest"
  #容器的名称  
    container_name: "php"
  #暴露给服务的端口  
    expose:
      - "9000"
   #绑定的主机目录   
    volumes: 
      - "/data/web/html:/web/html"
    #这是链接的网络
    networks:
     - "cmcc"


  mysql:
    #镜像名称 
    image: "mysql:5.7.27"
    #容器的名称
    container_name: "mysql"
    #环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=53gVeWDVGPjJ5kzH
    #暴露给内部服务的端口  
    expose:
      - "3306"
    #与主机共享进程命名空间  
    pid: "host"  
    #这是链接的网络
    networks:
     - "cmcc"

#设置网络     
networks:
   cmcc:
